# Generated by Django 5.2.5 on 2025-09-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=50, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_increment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('auction_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_relist', models.BooleanField(default=False)),
                ('shipping_options', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_district', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_location', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_estimate', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_handling', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_option', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=255, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('auction_terms', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('shipping_terms', models.TextField(blank=True, null=True)),
                ('warranty_terms', models.TextField(blank=True, null=True)),
                ('has_warranty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
