# Generated by Django 5.2.5 on 2025-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auctionproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
