# Generated by Django 5.2.5 on 2025-09-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_auctionproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='image',
        ),
        migrations.CreateModel(
            name='AuctionProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.auctionproduct')),
            ],
        ),
    ]
