# Generated by Django 5.2.5 on 2025-09-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_auctionproduct_image_auctionproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='max_relist',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='relist_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
