# Generated by Django 5.2.5 on 2025-09-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auctionproduct_max_relist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='max_relist',
        ),
        migrations.RemoveField(
            model_name='auctionproduct',
            name='relist_count',
        ),
    ]
