# Generated by Django 5.2.5 on 2025-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_auctionproduct_max_relist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='max_relist',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='relist_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
