# Generated by Django 5.2.5 on 2025-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auctionproduct_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
