# Generated by Django 5.2.5 on 2025-09-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auctionproduct_is_unsold_auctionproduct_winner'),
        ('products', '0009_auctionproduct_view_count'),
    ]

    operations = [
    ]
