# Generated by Django 5.2.5 on 2025-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
