# Generated by Django 5.2.5 on 2025-09-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailotp_last_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('password_reset', 'Password Reset')], default='verify_email', max_length=20),
        ),
    ]
