# Generated by Django 5.2.5 on 2025-09-20 03:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auctionproduct_max_relist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_winning', models.BooleanField(default=False)),
                ('is_auto_bid', models.BooleanField(default=False)),
                ('user_profile_snapshot', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='products.auctionproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-bid_time'],
                'indexes': [models.Index(fields=['product', 'bid_time'], name='auctions_bi_product_6d2da5_idx'), models.Index(fields=['user', 'bid_time'], name='auctions_bi_user_id_f7b931_idx')],
            },
        ),
    ]
