# Generated by Django 5.2.5 on 2025-09-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
