# Generated by Django 5.2.5 on 2025-09-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_total_amount'),
    ]

    operations = [
    ]
