# Generated by Django 5.2.5 on 2025-09-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_starting_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid_time']},
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
