version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 auctionhub.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=auctionhub.settings

  redis:
    image: redis:7
    ports:
      - "6379:6379"

#  celery:
#    build: .
#    command: celery -A auctionhub worker -l info
#    volumes:
#      - .:/app
#    depends_on:
#      - web
#      - redis
#    env_file:
#      - .env
#
#  celery-beat:
#    build: .
#    command: celery -A auctionhub beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#    volumes:
#      - .:/app
#    depends_on:
#      - web
#      - redis
#    env_file:
#      - .env
